// --- 2. APPLICATION STATE ---
export const state = {
    cards: [],
    basket: [],
    siteContent: { title: "Loading...", subtitle: "", groupSubtitles: {}, groupBanners: {}, infoText: "", disclaimerText: "", memberQuotes: {} },
    metadata: { groupOrder: [], memberOrder: {}, albums: {}, memberSignatures: {}, groupLogos: {} },
    user: null,
    isAdminView: false,
    adminFilters: { group: 'All', member: 'All', status: 'All', searchTerm: '' },
    adminSort: { by: 'default', order: 'asc' },
    adminSelectedIds: new Set(),
    isDataReady: { cards: false, content: false, metadata: false },
    carouselPages: {},
    userFilters: {},
    activeMemberSectionId: null,
};

// --- 3. DOM ELEMENT CACHE ---
export const dom = {
    userView: document.getElementById('user-view'),
    adminView: document.getElementById('admin-view'),
    collectionContainer: document.getElementById('collection-container'),
    siteTitle: document.getElementById('site-title'),
    siteSubtitle: document.getElementById('site-subtitle'),
    headerScrollArrow: document.getElementById('header-scroll-arrow'),
    floatingBasket: document.getElementById('floating-basket'),
    floatingEmptyBtn: document.getElementById('floating-empty-btn'),
    basketInfo: document.getElementById('basket-info'),
    floatingNavContainer: document.getElementById('floating-nav-container'),
    floatingNavContent: document.getElementById('floating-nav-content'),
    navToggleBtn: document.getElementById('nav-toggle-btn'),
    filterSidebar: document.getElementById('filter-sidebar'),
    filterBubble: document.getElementById('filter-bubble'),
    closeFilterBtn: document.getElementById('close-filter-btn'),
    filterForm: {
        search: document.getElementById('filter-search'),
        album: document.getElementById('filter-album'),
        version: document.getElementById('filter-version'),
        tags: document.getElementById('filter-tags'),
    },
    tutorialOverlay: document.getElementById('tutorial-overlay'),
    tutorialBubble: document.getElementById('tutorial-bubble'),
    tutorialContent: document.getElementById('tutorial-bubble-content'),
    tutorialNextBtn: document.getElementById('tutorial-next-btn'),
    tutorialCloseBtn: document.getElementById('tutorial-close-btn'),
    tutorialCloneContainer: document.getElementById('tutorial-clone-container'),
    infoBubble: document.getElementById('info-bubble'),
    adminBubble: document.getElementById('admin-panel-bubble'),
    modals: {
        basket: document.getElementById('basket-modal-overlay'),
        info: document.getElementById('info-modal-overlay'),
        adminForm: document.getElementById('admin-form-modal-overlay'),
        imagePreview: document.getElementById('image-preview-modal-overlay'),
        contentEditor: document.getElementById('content-editor-modal-overlay'),
        confirmation: document.getElementById('confirmation-modal-overlay'),
        login: document.getElementById('login-modal-overlay'),
        disclaimer: document.getElementById('disclaimer-modal-overlay'),
    }
};